### ISSUE TITLE
ps2link not responding at all

### ISSUE THREAD

**Issue by rwf93** [ps2dev/ps2link#16]
ps2link is not responding to ps2client at all

I have the ip set to `192.168.0.11` in the `IPCONFIG`

on my linux system I have the ipv4 address set to the ip above, default subnetmask and default gateway (same goes for inside `IPCONFIG`)

ps2link seems to return that it succeeded (ps2client exists the program gracefully.)

here are screenshots of stuff:

https://eatcaribou65.u.catgirlsare.sexy/AB72Gq5w.png
https://eatcaribou65.u.catgirlsare.sexy/2uxKWaAV.png

`IPCONFIG`

https://eatcaribou65.u.catgirlsare.sexy/Q-oUqr49.png

https://eatcaribou65.u.catgirlsare.sexy/sWsKR0xJ.png

the distro of debian i am using is `Linux Mint Cinnamon` 

Edit:

I've also tried recompiling & reinstalling ps2sdk as well, nothing fixed it still.

**Comment by rwf93** [comment]
resolved by stopping the thread from exiting & adding sleepthread to main.c

**Comment by sp193** [comment]
You set your PC to use the same IP address as the PS2? It wouldn't have worked then.
