### ISSUE TITLE
How do you send a udp/tcp packet to your pc with ps2dev?

### ISSUE THREAD

**Issue by jmoseman01** [ps2dev/ps2link#17]

**Comment by fjtrujy** [comment]
The PS2SDK & PS2LInk are not prepared to do something like this currently

**Comment by jmoseman01** [comment]
Don't you have tcpip and aren't you using rpc to communitcate also smb works.  Why can't I make a socket from the ps2 to my pc?

**Comment by jmoseman01** [comment]
I found the network example in the samples of the docker container.
