### ISSUE TITLE
 ps2link port number(s) and type (UDP/TCP)

### ISSUE THREAD

**Issue by jumpingbrowntrout** [ps2dev/ps2link#20]
Hi, what port number does ps2link listen on and what type of traffic is it (UDP/TCP)?
I need to create some port translations but cannot find the port information anywhere.
Thanks :)

**Comment by fjtrujy** [comment]
Here you have it!

https://github.com/ps2dev/ps2link/blob/a9fd0e7bf909cf917f6d3baf6099ffcedcdc606c/include/hostlink.h#L8-L10

And as the readme says:
```
PS2Link is a 'bootloader' which, used together with an Ethernet driver and a TCP/IP stack, enables you to download and execute software on your PS2.
```
So I would say that it is `TCP`

Thanks
